data_loader:
  name: MNIST

pre_processing:
  name: norm
  processed_path: data/MNIST/processed

modeling:
  structure:
    name: cnn 
    input_size_w: 28
    input_size_h: 28
    num_layers: 2
    kernel_size: 5
    channels: 26
    dropout: 0.3
    hidden_size: 64
    output_size: 10
  
  training:
    name: dnn
    criterion: cross_entropy_loss
    learning_rate: 0.001
    num_epochs: 10
    es_patience: 5
    batch_size: 64

  inference:
    name: dnn_class
    batch_size: 64

metrics:
  name: multi_class
